### PR TITLE
Portuguese strings updated

### PR DESCRIPTION
**Pull request by Mafarricos**

### CODE REVIEW

**Comment by lambda81** [comment]
I have not added this pull request for a reason.
Genesis has been updated to version 5 and it now uses different sting numbers and po format.
A new portuguese translation is more than welcome:)

https://www.transifex.com/tv-addons/genesis/

**Comment by Mafarricos** [comment]
Already requested to be on the team to translate portuguese :)

**Comment by lambda81** [comment]
You have been added to portuguese translation.
Please let me know if you have any issue.

**Comment by Mafarricos** [comment]
OK, let's translate :+1:

**Comment by Mafarricos** [comment]
100% ;)

**Comment by lambda81** [comment]
Nice:)
In will release a new version tomorrow and I am going to include it.
Thank you.

**Comment by s7eele** [comment]
tomorrow? awesome, left some notes u know where:)

**Comment by lambda81** [comment]
Added in version 5.0.1

**Comment by Mafarricos** [comment]
Thanks! :)

**Pull request closed without merging**
