### PR TITLE
updated default.py

### PR DESCRIPTION
**Pull request by jsergio123**
fixed the no stream issues

### CODE REVIEW

**Comment by lambda81** [comment]
I am re-coding a lot of stuff right now, I will release a new version this weekend and it will have new code for scrapers, resolvers and other stuff.
I will this scraper fixed in the new version.

**Comment by jsergio123** [comment]
I have fixed the search list too. Let me know if you want me submit those changes as well.

**Comment by lambda81** [comment]
I have pushed your update.

**Comment by jsergio123** [comment]
Great. Thanks for all your hard work.

**Pull request closed without merging**
