### PR TITLE
trakt.tv movie and tv shows recommendations

### PR DESCRIPTION
**Pull request by fopina**
Added trakt.tv recommendations to My Genesis

Trakt recommendations are far from good (very very far from jinni) but it doesn't hurt to have the option to check them out directly from the couch (especially as the website itself only shows 4 and the API provides 10, so Genesis is even better than the site to check recommendations :))

Sorry for the trimming on lines with whitespace in the end, Atom does that without asking.
Let me know if you prefer that I restore them to reduce differences but I guess Atom is right :)

### CODE REVIEW

**Comment by fopina** [comment]
Ah, the logos are missing because I don't have the base images nor I know the fonts used..

**Comment by lambda81** [comment]
I don't have the psd's of all themes too:)
When the theme attributors give them to me I will add these sections.

**Comment by fopina** [comment]
Ok, just let me know if I can help with anything :)

**Comment by sooty** [comment]
I have a lot of TV shows in my library but they have stopped auto updating is this something my end or yours ...
Genesis is an awesome tool thanks in advance

**Comment by s7eele** [comment]
hi @sooty, autoupdate is working fine for me and I haven't seen any issue being reported so it's most likely an issue on your end, regardless issues like yours are best dealt with on the TVADDONS forum, your issues will get much more visibility there as well so suggest you register and post if you haven't already http://forums.tvaddons.ag/register.php?referrerid=3871

sorry for adding clutter to this or :/

**Comment by sooty** [comment]
Hi thanks for reply and info it seems I may have been the problem for some reason the tvdb had disappeared so I had too re add it thanks for your time anyway and I will in future reference use tvaddons 👍

**Comment by lambda81** [comment]
nice to see you have made it working:)

**Comment by lambda81** [comment]
Recommendations added in version 5.
I am not adding the pull request because it can't be merged to the new code of 5.

**Pull request closed without merging**
