### PR TITLE
Bugfix: Portuguese and Brazilian subtitles search not working

### PR DESCRIPTION
**Pull request by Mafarricos**
You had the por,pob or pob,por for Portuguese and Brazilian subtitles, but you forgot to split the search results to this cases.
The addon was returning only english subtitles if I use Main Portuguese secondary English.

All other cases would work because you don't have any mashup of 2 languages separated by comma.

### CODE REVIEW

**Comment by fopina** [comment]
:+1:  on this pull :)

**Comment by lambda81** [comment]
I've pushed an update (version 4.8.3) before looking my pull requests:(
I will add it in version 4.8.4

**Comment by Mafarricos** [comment]
Thanks :+1:

**Comment by lambda81** [comment]
Added in version 4.8.4
I am closing this pull request.

**Comment by Mafarricos** [comment]
Thanks!

**Pull request closed without merging**
