### PR TITLE
update on regex to ftp folders

### PR DESCRIPTION
**Pull request by Mafarricos**
on openelec i get ftp://user:pass@ftp_site/folder
on windows i get ftp://user:pass@ftp_site:21/folder

This way it will work to both systems.

### CODE REVIEW

**Comment by lambda81** [comment]
I've pushed version 4.8.1 today.
I will add it in next update.
Thanks my friend.

**Comment by Mafarricos** [comment]
No prob, did you check my comment on the other PR? About movie25 or watchfree ;)

**Comment by lambda81** [comment]
yes, I replied there:)

**Comment by Mafarricos** [comment]
You also added this :)

**Pull request closed without merging**
