### PR TITLE
genesis improvement: strm files can be saved on ftp folder

### PR DESCRIPTION
**Pull request by Mafarricos**
as is ftp port must be 21, and uses standard ftp, no secure ftp.
But code can be improved to work with sftp if necessary.

The initial problem is that xbmcvfs.mkdir doesn't create folder over ftp.

This improvement permits to have a ftp folder with all strm files and share with different kodi's in the house.

### CODE REVIEW

**Comment by lambda81** [comment]
I've just logged in to github after a week and saw your pull request.
how are you my friend. we haven't talked for a while:)
I am re-coding a lot of stuff right now, I will release a new version this weekend and it will have new code for scrapers, resolvers and other stuff. I will try to add it in this version.

**Comment by Mafarricos** [comment]
It's a simple code, so I believe that it can get space on your new code ;)
If not in this version check if is good enough for the next one.
That way I can start using the strm files on ftp folder and share with my TV's :)

Keep up the excellent work.

**Comment by Mafarricos** [comment]
So many work in new 4.8.0 :D
Already checked the in plugin.video.genesis/modules/v4/__init__.py you have the code that i suggested. Will test it and close this PR is all is OK :)

**Comment by lambda81** [comment]
It's only the start:) All v4 package will be re-coded:)
Please let me know if strm files in ftp are now working,

**Comment by Mafarricos** [comment]
Already tested in more systems, was missing this:
https://github.com/lambda81/lambda-addons/pull/30

**Comment by Mafarricos** [comment]
A bit offtopic: In my opinion changing movie25 to watchfree as source of movies is a bad choice, if you have setup to HD only movies, you will get on the list CAM releases anyway.
With me movie25 as indexer worked, why the change?

**Comment by lambda81** [comment]
movies25 added cloudflare protection. It can be bypassed.
The problem that it can't work in UK anymore, it is blocked by ISP's and proxies can't work with it.
It is importand having sections (unlike sources) that work everywhere.
watchfree = primewire database.

**Comment by lambda81** [comment]
I couldn't find any better database. If you find any please let me know:)
I will definately change it:)

**Comment by Mafarricos** [comment]
Did you check http://www.vcdq.com/
You can use something like this:
http://www.vcdq.com/browse/1/0/3_2/10_9_21_22_23_24_6_28_32_19_11_3_2/0/2012_2013_2014_2015/0/0/0/
I think they usually are updated, but probably you have to suppress duplicate movies, as they list differet releases.
Or other types of filters, on my addon I use this one with complement of others ;)

**Comment by lambda81** [comment]
I even have the code for it:)
The problems:
it goes offline frequently.
There are movies missing there.
I am not talking about missing cams (I hate cams lol), I am talking about missing hd releases.
I am thinking to use icefilms, but there are some missing movies there too.

**Comment by lambda81** [comment]
I know all the sources you use in movie releases addon:)
Most of them are "blogs" and everytime I added that kind of websites as a source in Genesis, they went offline because of traffic lol

**Comment by Mafarricos** [comment]
LOL ;)
No problem, that way is impossible to get good sources :P
As movie releases is little I mashup up many sources so I try to get only hd movies, but if you did that on Genesis you would bring down all sites and blogs ;)

**Comment by lambda81** [comment]
I have tried a lot of them:)
I will keep searching though, I will keep watchfree until I find something better.
I was in a hurry to find something working today because the section was broken.
If you find anything please let me know:)

PS: movie releases is a cool addon:)
I love it:)

**Comment by Mafarricos** [comment]
Eheh, I think mine is almost used only by friends :P
It only exists because of yours ;)

**Comment by Mafarricos** [comment]
Will close this, already in your main release.

**Pull request closed without merging**
