### PR TITLE
unittests

### PR DESCRIPTION
**Pull request by fopina**
Re-did #28 for the new structure

### CODE REVIEW

**Comment by lambda81** [comment]
I've pushed an update (version 4.8.3) before looking my pull requests:(
I will add it in version 4.8.4

**Comment by fopina** [comment]
With these tests (still need some tweaking) you can then use Travis like https://travis-ci.org/fopina/lambda-addons and http://traviscron.pythonanywhere.com to trigger the build weekly or so to keep up with broken sources

**Comment by lambda81** [comment]
I have downloaded it and I am using it.
It works very good:) I love it:)
My only concern is that it may not be a good idea distributing it with the addon.
This is what I am talking about
https://github.com/fopina/lambda-addons/blob/782974908e8d7feeac770948795625e3d99cd39d/plugin.video.genesis/tests/test_sources.py#L36
Having included in the code searching/testing for specific movies/episodes may make the addon more vulnerable...

**Comment by fopina** [comment]
You're right, it makes no sense to distribute the unittests but I wasn't sure how you package the addons but assuming you simply do a zip on the repository plugin directory, maybe we could just move the tests folder to the root of the repository.  So

    lambda-addons/tests/plugin.video.genesis/test_*.py

Does that sound better?

It could also be in a different repository (lambda-addons-tests?) that could even contain a git submodule pointing to lambda-addons but I think it makes sense to keep them in same repository as it makes it easier to have them keep up with the actual plugin (in branching, tagging, etc)..

And, yeah, scrape tests are hard to come up if we don't have static content we can rely on :\  
I use different movies because I manually checked which movies exist in each source and don't to make sure each test contained a valid movie search.
Assuming that these sites might change sources listed for each movie but won't "remove" the actual movie, they should valid tests. The main issue is with their uptime reliability as tests might fail due to connection errors or so and that can't be seem as all exceptions are suppressed in the code :P

But I guess for each test there could simple status check (like request.get(source.base_link)) and assertFail with specific error message so it could easily be checked in travis (or any other CI or manual test execution) instead of simply asserting "works or not"

**Comment by s7eele** [comment]
sounds cool

**Comment by fopina** [comment]
Re-integrated with master branch (for 4.8.4) and re-organized the folder structure as mentioned.

**Comment by lambda81** [comment]
The only real issue is the static content.
How about getting random movies/episodes by calling specific sections from the addon in order to get them?
We can search more than once every source, so there has to be at least 1 valid search.
The good thing with the move is that it will be merged it even if I push an update:)

**Comment by fopina** [comment]
"random" rarely sounds good for an unit test :S
but yes, static content in this case doesn't either..

I'll try to take a closer look to each test that is failing and
understanding why, because I don't think it's because of the content but
because of "server down" or errors like those (which should still raise an
error, but could be different one so it was clear..)

Otherwise we can try "random", such as using "latest movies" (trakt
featured) and going through 1 page of them, but not sure if that'll work
for some of the sources (like the indian-only one..)

**Comment by lambda81** [comment]
a reason for failing may be the timeout that is being used for every http request on sources.
it's 5 seconds. when testing them "locally" I increase it to 30 seconds.
A good section for testing is also the box office section.

**Comment by fopina** [comment]
currently it's calling the source class directly, not through the threads,
so it's not affected by the timeout settings..

**Comment by lambda81** [comment]
I am not talking this timeout.
https://github.com/lambda81/lambda-addons/blob/master/plugin.video.genesis/modules/libraries/client.py#L101

**Comment by fopina** [comment]
Ah ok :)
The problem with using several movies taken from box office is that the
tests won't be able to assert the middle steps in the sources (like find
the movies before listing the sources)..
It will all be one big step. But I'll try it

**Comment by fopina** [comment]
How does it look now then?

**Comment by fopina** [comment]
4 sources are giving errors at the moment. alluc has the API down (I think I haven't seen it it up yet), moviestorm won't allow consecutive searches (which messes up the whole box office list iteration) and the other two seem to be not working actually (yifystreams seems to have changed the page and movietube domain is down).
https://travis-ci.org/fopina/lambda-addons

But looks useful now

**Comment by dlrtyblrdz** [comment]
Hi buddy,  i just wanted to say thank you for genesis.  I love the work you do.  Will you b releasing a new version soon?  I am noticing a lot of hd links need updated resolvers.

thanks again for your work

Dlrtyblrdz from tvaddons

**Comment by lambda81** [comment]
@fopina, version 5 has been released and it unitests would need to be updated.
if you need any help let me know

**Comment by fopina** [comment]
Moved to #53 as the branch cannot be updated with too many conflicts..

**Pull request closed without merging**
